### PR TITLE
Timer

### LINKED ISSUE #13: deltaTime is incorrect
The system deltaTime value constantly grows instead of being a difference in frame update time.

### LINKED ISSUE #14: didEnter is not called for initial scene
The initial scene does not get the  `didEnter` method called, leading to incorrect state initialization.

### PR DESCRIPTION
**Pull request by RyanBradshaw1**
Added **countdown timer** that starts at _60_ and counts down to _0_.

### CODE REVIEW

File: src/simplify.js [hunk 1]
```diff
@@ -96,16 +96,29 @@ const TitleScene = {
 
 const PlayScene = {
   // state that is local to the scene
-  state: {},
+  state: {
+    time: 0
+  },
   // called once when the engine transitions to this scene
-  didEnter(system) {},
+  didEnter(system) {
```
Comment (RichardMarks) [inline src/simplify.js:101]: It would be a good idea to initialize the state in this method so that when we later return to the PlayScene from another scene, the state is reset as expected.

```js
PlayScene.state.time = 0;
```

File: src/simplify.js [hunk 2]
```diff
@@ -96,16 +96,29 @@ const TitleScene = {
...
   didExit(system) {
     // set local state to null to free the memory usage of the local state
     PlayScene.state = null;
   },
   // called every frame of the engine main loop
-  didUpdate(system) {},
+  didUpdate(system) {
+    system.ctx.clearRect(0, 0, SCREEN_WIDTH, 60)
+    PlayScene.state.time += system.deltaTime
+    // console.log(PlayScene.state.time)
```
Comment (RichardMarks) [inline src/simplify.js]: It is good practice to remove your console logs before opening a pull request, unless you have a good reason to retain them, in which case an explanation comment preceding the log statement line should be provided.

File: src/simplify.js [hunk 3]
```diff
@@ -96,16 +96,29 @@ const TitleScene = {
...
+    system.ctx.font = "40px serif"
+
+    PlayScene.state.time < 59
```
Comment (RichardMarks) [inline src/simplify.js]: It is good practice to avoid _magic numbers_ in expressions by creating a constant and using that instead.

```js
const PLAY_TIME_SECONDS = 59;
```

File: src/simplify.js [hunk 4]
```diff
@@ -96,16 +96,29 @@ const TitleScene = {
...
+      ? system.ctx.fillText(Math.floor(61 - PlayScene.state.time), 350, 40)
```
Comment (RichardMarks) [inline src/simplify.js]: For the `61` here, you should use the constant mentioned previously in the calculation.

**Review by RichardMarks — CHANGES_REQUESTED** [review]
image

You should make sure that you have this extension installed in your Visual Studio Code.
If you are not using VSCode, you should find a Prettier plugin so that your code can be formatted to match.

Approval of this PR is pending changes mentioned. Overall great work and thank you for your contribution.

**Review by RichardMarks — APPROVED** [review]
